### PR TITLE
adi_update_boot.sh: update script

### PR DESCRIPTION
**Pull request by SRaus**
Update adi_update_boot.sh script by adding help section,
extra checking, and a parameter ('dev'/'master') for being
able to use latest boot files from master too, beside
latest released files.

Signed-off-by: stefan.raus <stefan.raus@analog.com>

### CODE REVIEW

**Review by mhennerich — COMMENTED** [review]
Looks good to me, however can we check if enough space is available?

OT.BIN: Wrote only 1536 of 10240 bytes
tar: zynq-zed-adv7511-ad936x-fmcomms2-3-4/bootgen_sysfiles.tgz: Cannot write: No space left on device
.tar: zynq-zed-adv7511-ad9467-fmc-250ebz: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-ad9467-fmc-250ebz: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-ad9467-fmc-250ebz/BOOT.BIN: Cannot open: No such file or directory
tar: zynq-zed-adv7511-ad9467-fmc-250ebz: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-ad9467-fmc-250ebz/bootgen_sysfiles.tgz: Cannot open: No such file or directory
tar: zynq-zed-adv7511-ad9467-fmc-250ebz: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-ad9467-fmc-250ebz/devicetree.dtb: Cannot open: No such file or directory
tar: zynq-zed-adv7511-adrv9002: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-adrv9002: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-adrv9002/BOOT.BIN: Cannot open: No such file or directory
tar: zynq-zed-adv7511-adrv9002: Cannot mkdir: No space left on device
.tar: zynq-zed-adv7511-adrv9002/bootgen_sysfiles.tgz: Cannot open: No such file or directory
tar: zynq-zed-adv7511-adrv9002: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-adrv9002/zynq-zed-adv7511-adrv9002: Cannot mkdir: No such file or directory
tar: zynq-zed-adv7511-adrv9002: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-adrv9002/zynq-zed-adv7511-adrv9002/devicetree.dtb: Cannot open: No such file or directory
tar: zynq-zed-adv7511-adrv9002: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-adrv9002/zynq-zed-adv7511-adrv9002-rx2tx2: Cannot mkdir: No such file or directory
tar: zynq-zed-adv7511-adrv9002: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-adrv9002/zynq-zed-adv7511-adrv9002-rx2tx2/devicetree.dtb: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0363: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0363: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0363/BOOT.BIN: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0363: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0363/devicetree.dtb: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0363: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0363/bootgen_sysfiles.tgz: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0506-mii: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0506-mii: Cannot mkdir: No space left on device
.tar: zynq-zed-adv7511-cn0506-mii/BOOT.BIN: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0506-mii: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0506-mii/devicetree.dtb: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0506-mii: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0506-mii/bootgen_sysfiles.tgz: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0506-rgmii: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0506-rgmii: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0506-rgmii/BOOT.BIN: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0506-rgmii: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0506-rgmii/bootgen_sysfiles.tgz: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0506-rgmii: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0506-rgmii/devicetree.dtb: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0506-rmii: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0506-rmii: Cannot mkdir: No space left on device
.tar: zynq-zed-adv7511-cn0506-rmii/BOOT.BIN: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0506-rmii: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0506-rmii/devicetree.dtb: Cannot open: No such file or directory
tar: zynq-zed-adv7511-cn0506-rmii: Cannot mkdir: No space left on device
tar: zynq-zed-adv7511-cn0506-rmii/bootgen_sysfiles.tgz: Cannot open: No such file or directory
tar: zynq-zed-imageon: Cannot mkdir: No space left on device
tar: zynq-zed-imageon: Cannot mkdir: No space left on device
tar: zynq-zed-imageon/BOOT.BIN: Cannot open: No such file or directory
tar: zynq-zed-imageon: Cannot mkdir: No space left on device
tar: zynq-zed-imageon/devicetree.dtb: Cannot open: No such file or directory
tar: zynq-zed-imageon: Cannot mkdir: No space left on device
tar: zynq-zed-imageon/bootgen_sysfiles.tgz: Cannot open: No such file or directory
tar: Exiting with failure status due to previous errors
Extraction failed - aborting
root@analog:~/linux_image_ADI-scripts#

**Comment by SRaus** [comment]
Actually, I realized now that there may be a problem due to different size of boot partition in older releases (1 GB) vs master and next releases (2GB). When updating an older SD Card with latest master files (or next releases), script will fail at unzipping since files won't fit.

What do you think of adding a restriction in order to not allow having boot files from a release with root fs from another release?

**Comment by mhennerich** [comment]
> What do you think of adding a restriction in order to not allow having boot files from a release with root fs from another release?

Well, I don't think this is necessary, but we need to make sure that there is enough free space available before we start unzipping.

**Comment by SRaus** [comment]
> > What do you think of adding a restriction in order to not allow having boot files from a release with root fs from another release?
> 
> Well, I don't think this is necessary, but we need to make sure that there is enough free space available before we start unzipping.

Implemented.

**Review by mhennerich — APPROVED** [review]

**Pull request merged**
